export const margins = {
  nano: "4px",
  mini: "8px",
  small: "16px",
  medium: "24px",
  large: "30px",
  big: "40px",
  extraLarge: "70px",
  huge: "100px",
  gigantic: "120px",
};

export const zIndex = {
  forground: 10,
  mid: 20,
  inFront: 30,
  onTop: 40,
  overCharacter: 41,
  background: 0,
  backgroundTwo: 1,
  character: 2,
  hair: 3,
  mask: 4,
  styleline: 5,
  filter2: 6,
  addOns: 7,
  filter1: 8,
  clothing: 9,
  headPiece: 10,
};
