compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

# commented in favor of package.json's packageManager property
# yarnPath: .yarn/releases/yarn-4.0.0.cjs
