compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

# TODO: remove azure dependency
npmScopes:
  kryha:
    npmRegistryServer: "https://pkgs.dev.azure.com/Kryha-io/_packaging/Kryha-io/npm/registry"

yarnPath: .yarn/releases/yarn-4.0.0.cjs
