FROM node:18-alpine as build

RUN apk --no-cache add --update git python3 make g++

WORKDIR /usr/main/

RUN yarn set version 2 --only-if-needed

ENV GENERATE_SOURCEMAP true

ARG VITE_RPC
ENV VITE_RPC $VITE_RPC

ARG VITE_BRIDE_HREF
ENV VITE_BRIDE_HREF $VITE_BRIDE_HREF

ARG VITE_BASE_URL
ENV VITE_BASE_URL $VITE_BASE_URL

COPY .yarnrc.yml ./.yarnrc.yml
COPY yarn.lock ./yarn.lock
COPY .yarn/ ./.yarn/

COPY .eslintrc.json ./.eslintrc.json
COPY .eslintignore ./.eslintignore

COPY index.html ./index.html

COPY package.json ./package.json

COPY tsconfig.json ./tsconfig.json
COPY tsconfig.node.json ./tsconfig.node.json

COPY vite.config.ts ./vite.config.ts

COPY public/ ./public/
COPY src/ ./src/

RUN yarn install --silent

RUN NODE_OPTIONS='--max-old-space-size=4096' yarn build

FROM nginx:1.21-alpine as run

RUN sed -i '/location \//a try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf

COPY --from=build /usr/main/dist/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
