apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: character-builder-ui
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: kread.azurecr.io/frontend
      docker:
        dockerfile: Dockerfile.ui
        buildArgs:
          VITE_RPC: "emerynet.rpc.agoric.net"
          VITE_BRIDGE_HREF: "" 
          VITE_BASE_URL: "kryha.kread.dev"
          NETWORK_CONFIG: "emerynet"
deploy:
  kustomize:
    paths:
      - ../deployment/emerynet/workloads
    defaultNamespace: agoric-makefile-automation

