trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build_and_deploy
    displayName: Build and Deploy
    dependsOn: []
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: build_and_deploy
        displayName: Build Docker images and deploy through Kubernetes
        steps:
          - script: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
            displayName: Install Skaffold
          - task: Docker@2
            displayName: Login to Container Registry
            inputs:
              command: login
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION)
          - task: DownloadSecureFile@1
            name: authkey
            displayName: "Download Service Account Key"
            inputs:
              secureFile: web3-agoric.json
              retryCount: "2"
          - script: gcloud auth activate-service-account  web3-agoric-0@web3-335312.iam.gserviceaccount.com --key-file=$(authkey.secureFilePath)
            displayName: Activate Service Account
          - task: Kubernetes@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "gke-service-connection"
              namespace: "agoric-makefile-automation"
              command: "login"
          - script: |
              cd frontend
              export $(grep -v '^#' .env.devnet | xargs)
              envsubst < ../deployment/devnet/workloads/config/ui-config.template.yaml > ../deployment/devnet/workloads/config/ui-config.yaml
              envsubst < skaffold.devnet.template.yaml > skaffold.devnet.yaml
              skaffold run --filename skaffold.devnet.yaml
            displayName: Build and push docker images
