name: CI/CD Emerynet

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin/
      shell: bash

    - name: Login to Container Registry
      run: docker login -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      env:
        DOCKER_CLI_ACI_SERVER: ${{ secrets.CONTAINER_REGISTRY_SERVER }}
      shell: bash

    - name: Download Service Account Key
      uses: actions/checkout@v2
      with:
        path: ${{ runner.workspace }}/authkey
      env:
        GCP_AUTH_KEY: ${{ secrets.GCP_AUTH_KEY }}
      shell: bash

    - name: Activate Service Account
      run: gcloud auth activate-service-account web3-agoric-0@web3-335312.iam.gserviceaccount.com --key-file=$GITHUB_WORKSPACE/authkey/web3-agoric.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/authkey/web3-agoric.json
      shell: bash

    - name: Login to Kubernetes
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        cluster-context: "gke-service-connection"
        namespace: "agoric-makefile-automation"

    - name: Build and push Docker images
      run: |
        cd frontend
        export $(grep -v '^#' .env.emerynet | xargs)
        envsubst < ../deployment/emerynet/workloads/config/ui-config.template.yaml > ../deployment/emerynet/workloads/config/ui-config.yaml
        envsubst < skaffold.emerynet.template.yaml > skaffold.emerynet.yaml
        skaffold run --filename skaffold.emerynet.yaml
      shell: bash
