trigger:
 - production

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build_and_deploy
    displayName: Build and Deploy
    dependsOn: []
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: build_and_deploy
        displayName: Build Docker images and deploy through Kubernetes
        steps:
          - script: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
            displayName: Install Skaffold
          - task: DownloadSecureFile@1
            name: authkey
            displayName: "Download Service Account Key"
            inputs:
              secureFile: web3-agoric.json
              retryCount: "2"
          - script: gcloud auth activate-service-account  web3-agoric-0@web3-335312.iam.gserviceaccount.com --key-file=$(authkey.secureFilePath)
            displayName: Activate Service Account
          - task: Kubernetes@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "gke-service-connection"
              namespace: "character-builder-prod"
              command: "login"
          - script: |
              cd frontend
              export $(grep -v '^#' .env.production | xargs)
              envsubst < ../deployment/production/workloads/config/ui-config.template.yaml > ../deployment/production/workloads/config/ui-config.yaml
              envsubst < skaffold.production.template.yaml > skaffold.production.yaml
              skaffold run --filename skaffold.production.yaml
            displayName: Build and push docker images
