export const routes = {
  root: "/",
  character: "/character",
  shop: "/shop",
  inventory: "/inventory",
  items: "/items",
  createCharacter: "/create-character",
  buyItem: "/buy-item",
  buyCharacter: "/buy-character",
  sellItem: "/sell-item",
  sellCharacter: "/sell-character",
  about: "/about",
  privacy: "/privacy",
  onboarding: "/onboarding",
  test: "/test",
};
