export const routes = {
  root: "/",
  connectWallet: "/connect-wallet",
  character: "/character",
  shop: "/shop",
  itemShop: "/shop/items",
  characterShop: "/shop/characters",
  inventory: "/inventory",
  inventoryItems: "/inventory/items",
  inventoryCharacters: "/inventory/characters",
  items: "/items",
  createCharacter: "/create-character",
  buyItem: "/buy-item",
  buyCharacter: "/buy-character",
  sellItem: "/sell-item",
  sellCharacter: "/sell-character",
  about: "/about",
  privacy: "/privacy",
  onboarding: "/onboarding",
  downloadCharacter: "/download-character",
  mobileNotAvailable: "/mobile-not-available",
} as const;
