export const character = {
  hair: "hair",
  noseline: "noseline",
  midBackground: "mid background",
  mask: "mask",
  headPiece: "head piece",
  frontMask: "front mask",
  liquid: "liquid",
  background: "background",
  airReservoir: "air reservoir",
  clothing: "clothing",
  equip: "equip",
  sell: "sell",
  choose: "choose",
  unequip: "unequip",
  story: "story",
  equippedItems: "equipped items",
  zeroOne: "01",
  zeroTwo: "02",
  zeroThree: "03",
  zeroFour: "04",
  zeroFive: "05",
  zeroSix: "06",
  creators: "creators",
  stats: "stats",
  items: "items",
  details: "details",
  project: "project",
  itemActivity: "item activity",
  deleteCharacter: "delete character",
  characters: "characters",
  defaultCharacter: "default character",
  noItemEquipped: "no item equipped",
  noItemEquippedCharacter: "this character has no items equipped",
  startEquipping: "start equipping",
  level: "level",
  levelInfo: "this is the level of your character...",
  buy: "buy",
  select: "select",
  selected: "selected",
  thereAreNoCharactersAvailable: "there are no characters available",
  minANewCharcater: "mint a new character",
  thereAreNoItemsInYourInventory: "there are no items in your inventory",
  buyItemsInTheStore: "buy items in the store",
};
