export const character = {
  hair: "hair",
  filter2: "filter 2",
  patch: "patch",
  mask: "mask",
  headPiece: "head piece",
  perk1: "perk 1",
  filter1: "filter 1",
  background: "background",
  perk2: "perk2",
  garment: "garment",
  equip: "equip",
  sell: "sell",
  choose: "choose",
  unequip: "unequip",
  story: "story",
  equippedItems: "equipped items",
  zeroOne: "01",
  zeroTwo: "02",
  zeroThree: "03",
  zeroFour: "04",
  zeroFive: "05",
  zeroSix: "06",
  creators: "creators",
  stats: "stats",
  items: "items",
  details: "details",
  project: "project",
  artistInfo: "artist information",
  itemActivity: "item activity",
  deleteCharacter: "delete character",
  characters: "characters",
  defaultCharacter: "default character",
  noItemEquipped: "no item equipped",
  noItemEquippedCharacter: "this character has no items equipped",
  startEquipping: "start equipping",
  level: "level",
  characterLevel: "character level",
  combinedItemLevel: "combined item level",
  levelInfo: "this is the level of your entire character, a combination of the character NFT level and all equipped items",
  characterLevelInfo: "this is the level of your character NFT",
  itemLevelInfo: "this is the level of all equipped items combined",
  buy: "buy",
  select: "select",
  selected: "selected",
  thereAreNoCharactersAvailable: "there are no characters available",
  minANewCharcater: "mint a new character",
  thereAreNoItemsInYourInventory: "there are no items in your inventory",
  buyItemsInTheStore: "buy items in the store",
  styleline: "styleline",
  background2: "background 2",
  addOns: "add-ons",
  youDoNotHave: "you do not own any characters",
  createANewCharacter: "create a new character",
  youDoNotOwnACharacter: "you do not own a character. Mint a character to continue.",
  noCharactersInInventory: "no characters in inventory",
  buyCharactersFromStore: "buy characters from the store",
};
