export const character = {
  hair: "hair",
  noseline: "noseline",
  midBackground: "mid background",
  mask: "mask",
  headPiece: "head piece",
  frontMask: "front mask",
  liquid: "liquid",
  background: "background",
  airResevoir: "air resevoir",
  clothing: "clothing",
  equip: "equip",
  sell: "sell",
  unequip: "unequip",
  story: "story",
  zeroOne: "01",
  zeroTwo: "02",
  zeroThree: "03",
  zeroFour: "04",
  zeroFive: "05",
  zeroSix: "06",
  creators: "creators",
  stats: "stats",
  items: "items",
  details: "details",
  project: "project",
  itemActivity: "item activity",
  deleteCharacter: "delete character",
  characters: "characters",
  defaultCharacter: "default character",
};
