export const content = {
  privacyAndTerms: "Privacy & terms",
  about: "about",
  weAreCommittedTo:
    "We are committed to protecting your personal information and your right to privacy. When you visit our website we appreciate that you are trusting us with your personal information. We take your privacy very seriously. If there are any terms in this privacy notice that you do not agree with, please discontinue use of our Services immediately.",
  whatInformationDoWe: "What information do we collect?",
  weCollectPersonal:
    "We collect personal information that you provide to us. We collect personal information that you voluntarily provide to us when you express an interest in obtaining information about us or our products and Services, when you participate in activities on the Website or otherwise when you contact us. The personal information that we collect depends on the context of your interactions with us and the Website, the choices you make and the products and features you use. The personal information we collect may include the following: Personal Information Provided by You. We collect names; email addresses; and other similar information. All personal information that you provide to us must be true, complete and accurate, and you must notify us of any changes to such personal information.Information automatically collected In Short: Some information — such as your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our Website. We automatically collect certain information when you visit, use or navigate the Website. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Website and other technical information. This information is primarily needed to maintain the security and operation of our Website, and for our internal analytics and reporting purposes. Like many businesses, we also collect information through cookies and similar technologies.",
  howDoWeUse: "how do we use your information?",
  inShortWeProcces:
    "In Short:  We process your information for purposes based on legitimate business interests, the fulfillment of our contract with you, compliance with our legal obligations, and/or your consent. We use personal information collected via our Website for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations. We indicate the specific processing grounds we rely on next to each purpose listed below.",
  weUseTheInformation: "We use the information we collect or receive:",
  toSendAdministrativeInformation:
    "to send administrative information to you. We may use your personal information to send you product, service and new feature information and/or information about changes to our terms, conditions, and policies.",
  toProtectOurServices:
    "to protect our Services. We may use your information as part of our efforts to keep our Website safe and secure (for example, for fraud monitoring and prevention). To enforce our terms, conditions and policies for business purposes, to comply with legal and regulatory requirements or in connection with our contract. To respond to legal requests and prevent harm. If we receive a subpoena or other legal request, we may need to inspect the data we hold to determine how to respond.",
};
