export const filters = {
  allCategories: "all categories",
  aToZ: "A to Z",
  highestPrice: "highest price",
  lowestPrice: "lowest price",
  rarity: "rarity",
  latest: "latest",
  color: "colors",
  sortBy: "sort by",
  price: "price",
  category: "category",
  categories: "categories",
  clearFilter: "clear all",
  apply: "apply",
  filters: "filters",
};
