export const general = {
  notFound: "This screen doesn't exist.",
  dataNotFound: "data not found",
  goHome: "Go to home screen",
  appName: "Agoric Character Builder",
  character: "character",
  characters: "characters",
  shop: "shop",
  inventory: "inventory",
  items: "items",
  details: "details",
  price: "price",
  color: "color",
  sortBy: "sort by",
  latest: "latest",
};
