import { MAX_CHARACTER_LENGTH, MINTING_COST_USD } from "../../constants";

export const general = {
  notFound: "this screen doesn't exist.",
  dataNotFound: "data not found",
  goHome: "go to home screen",
  appName: "KREAd",
  character: "character",
  characters: "characters",
  category: "category",
  categories: "categories",
  shop: "shop",
  inventory: "inventory",
  items: "items",
  details: "details",
  price: "price",
  color: "color",
  sortBy: "sort by",
  latest: "latest",
  equipped: "equipped",
  createNew: "create new",
  choose: "choose",
  sell: "sell",
  loadMore: "load more",
  info: "i",
  toolTipTitle: "tool tip title",
  toolTipInfo: "maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.",
  thisFieldIsRequired: "this field is required",
  mintNew: `mint new (IST)`,
  theMinimiumAmountIs: "the minimum amount is IST 1",
  moreInfo: "more info",
  thereAreNoAssetsAvailable: "there are no assets available",
  logo: "KREAd",
  aCharcterBuilderApp:
    "KREAd is a character builder dApp, where all the characters and their items are dynamic NFTs. You have the freedom to build your character and the ownership of all the equipment attached to it. So feel free to sell them, trade them, or even burn them!",
  sagesBy: "SAGES by KREAd",
  sagesIsTheFirst: "SAGES is the first collection launched on the KREAd dApp.\nStart collecting SAGES NFTs to\nshape your own saga.",
  explore: "explore",
  connectWallet: "connect Keplr Wallet",
  activateWallet: "activate Wallet",
  whoWeAre: "who we are",
  ourLeadership: "Our leadership includes some of\nthe most inventive and\nexperienced executives in the technology industry.",
  isPartOfAgoric: "KREAd is a decentralized application deployed on ",
  anOpenSource:
    ", an open-source development company launching an interoperable Proof-of-Stake chain and economy. The dApp is imagined, built, and designed by ",
  agoric: "Agoric",
  theSagesArt: "The SAGES art and comic is\ncreated by Enmanuel Heredia.",
  kryha: "Kryha",
  contactUs: "contact us",
  questionsBug: "questions, bug reports, \nfeedback... ? We are here for it all.",
  sendEmailTo: "send an email to",
  contactEmail: "kread@kryha.io",
  followUs: "Follow us",
  discord: "Discord",
  twitter: "Twitter",
  instagram: "Instagram",
  forSale: "for sale",
  createCharacter: "create character",
  thereIsNoActity: "there is no activity currently.",
  buy: "buy",
  comingSoon: "coming soon!",
  scroll: "scroll",
  maxCharacterLength: `the character name cannot be longer than ${MAX_CHARACTER_LENGTH} characters`,
  characterNamePatternError: "the character name can only contain alphanumeric characters, underscores(_)  and/or dashes(-)",
  goToYourWallet: "go to your wallet to accept the action!",
  yourActionIsPending: "your action is pending in your wallet. Please go and accept the action to be able to continue your experience.",
  loading: "loading...",
  next: "next",
  characterCardTitle: "mint a new character",
  characterCardInfo: `by clicking the button you will mint a new character. The cost of it is only IST ${MINTING_COST_USD}. Start now!`,
  createACharacterTitle: "character name",
  createACharacterInfo:
    "this is the name for your character. Think about something original since it needs to be unique; and keep in mind after setting it up you won't be able to change it! Your character name must be max 20 characters.",
  sellAssetTitle: "set price",
  sellAssetInfo:
    "add a selling price to your character/item. Keep in mind the level that it is as a reference, since it can help you to set a fair price in comparison of the rest of the characters/items.",
  viewCharacter: "view character",
  desktopOnly: "unfortunately, this experience can only be enjoyed on desktop devices.",
  moreAboutThisProject: "more about this project",
  backToMain: "back to main mode",
  backToCategories: "back to categories",
  activateSmartWallet: "your smart wallet is the key to your character",
  activateSmartWalletDescription:
    "Activate your smart wallet to manage your transactions on the Agoric chain. This will allow you mint your characters and store your character's items and progress. \n" +
    "\n" +
    "Click “Activate wallet” to get started.",
};
