export const general = {
  notFound: "this screen doesn't exist.",
  dataNotFound: "data not found",
  goHome: "go to home screen",
  appName: "Agoric Character Builder",
  character: "character",
  characters: "characters",
  shop: "shop",
  inventory: "inventory",
  items: "items",
  details: "details",
  price: "price",
  color: "color",
  sortBy: "sort by",
  latest: "latest",
  equipped: "equipped",
  showFull: "show full",
  createNew: "create new",
  choose: "choose",
  sell: "sell",
  category: "category",
  loadMore: "load more",
  info: "i",
  toolTipTitle: "tool tip title",
  toolTipInfo: "maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.",
  thisFieldIsRequired: "this field is required",
  mintNew: "mint new",
};
