export const item = {
  creators: "creators",
  level: "level",
  levelInfo: "This is the level of your item...",
  effectiveness: "effectiveness",
  effectivenessInfo: "This reflects how effective your item is...",
  layerComplexity: "layer complexity",
  layerComplexityInfo: "This tells you how complex your layer is...",
  forged: "forged",
  baseMaterial: "base material",
  colors: "colors",
  contractAddress: "contract address",
  boardId: "board id",
  artist: "artist",
  metadata: "metadata",
  event: "event",
  price: "price",
  from: "from",
  to: "to",
  date: "date",
  view: "view",
};
