export const item = {
  buy: "buy",
  creators: "creators",
  level: "level",
  levelInfo: "this is the level of your item...",
  effectiveness: "effectiveness",
  effectivenessInfo: "this reflects how effective your item is...",
  layerComplexity: "layer complexity",
  layerComplexityInfo: "this tells you how complex your layer is...",
  durability: "durability",
  durabilityInfo: "this level determines how resistant an item is to damage",
  weight: "weight",
  weightInfo: "mobility of the Item",
  sense: "sense",
  senseInfo: "sense levels increase your awareness to incoming threats",
  reserves: "reserves",
  reservesInfo: "the energy reservation levels of an item",
  filtering: "filtering",
  filteringInfo: "filter levels increase your resistance to toxicity",
  forged: "forged",
  baseMaterial: "base material",
  colors: "colors",
  contractAddress: "contract address",
  boardId: "board id",
  brand: "brand",
  boardIdHash: "#",
  artist: "artist",
  metadata: "metadata",
  event: "event",
  price: "price",
  from: "from",
  to: "to",
  date: "date",
  view: "view",
  story: "story",
  stats: "stats",
  project: "project",
  details: "details",
  itemActivity: "item activity",
  equip: "equip",
  unequip: "unequip",
  sell: "sell",
  zero: 0,
  noItemEquipped: "no item equipped",
  startEquipping: "start equipping",
  youDidNotEquip: "you did not equip any item yet. Your inventory is empty, start equipping some items and building your own characters!",
  selectAnItemFrom: "select an item from the the store",
  noItemsInInventory: "there are no items in the inventory",
  buyItemsFromStore: "buy items from the store",
};
