export const item = {
  buy: "buy",
  creators: "creators",
  level: "level",
  levelInfo: "this is the level of your item...",
  effectiveness: "effectiveness",
  effectivenessInfo: "this reflects how effective your item is...",
  layerComplexity: "layer complexity",
  layerComplexityInfo: "this tells you how complex your layer is...",
  forged: "forged",
  baseMaterial: "base material",
  colors: "colors",
  contractAddress: "contract address",
  boardId: "board id",
  brand: "brand",
  boardIdHash: "#",
  artist: "artist",
  metadata: "metadata",
  event: "event",
  price: "price",
  from: "from",
  to: "to",
  date: "date",
  view: "view",
  story: "story",
  stats: "stats",
  project: "project",
  details: "details",
  itemActivity: "item activity",
  equip: "equip",
  unequip: "unequip",
  sell: "sell",
  zero: 0,
  noItemEquipped: "no item equipped",
  startEquipping: "start equipping",
  youDidNotEquip: "you did not equip any item yet. Your inventory is empty, start equipping some items and building your own characters!",
  selectAnItemFrom: "select an item from the the store",
  noItemsInInventory: "no items in inventory",
  buyItemsFromStore: "buy items from the store",
  noCharactersInInventory: "no characters in inventory",
  buyCharactersFromStore: "buy characters from the store",
};
