export const itemSlots = {
  noselineCode: "nl",
  midBackgroundCode: "bg I",
  maskCode: "m",
  headPieceCode: "hp",
  hairCode: "h",
  frontMaskCode: "f",
  liquidCode: "l",
  backgroundCode: "bg II",
  airResevoirCode: "ar",
  clothingCode: "c",
  noseline: "noseline",
  midBackground: "background II",
  mask: "mask",
  headPiece: "head piece",
  hair: "hair",
  frontMask: "front mask",
  liquid: "liquid",
  background: "background I",
  airResevoir: "air resevoir",
  clothing: "clothing",
  filter: "filter I",
};
