export const store = {
  buyAtStore: "buy at store",
  min: "min",
  max: "max",
  buyMoreAtStore: "buy more at store",
  buyItem: "buy item",
  itemSuccessfullyBought: "item succesfully bought!",
  itemPlacedInShop: "item placed in the shop",
  itemSuccessfullyPlacedInShop: "item succesfully placed in the shop!",
  yourNewItemIs: "your new item is successfully bought.",
  checkItem: "check item",
  sellItem: "sell item",
  buyCharacter: "buy character",
  characterSuccessfullyBought: "character succesfully bought!",
  characterPlacedInShop: "character placed in the shop.",
  characterSuccessfullyPlacedInShop: "your character is succesfully placed in the shop!",
  yourNewCharacterIs: "your new character is successfully bought.",
  checkCharacter: "check character",
  sellCharacter: "sell character",
  setPrice: "set price",
  placeInShop: "place in shop",
  viewInShop: "view in shop",
  goToInventory: "go to inventory",
  noResults: "no results",
  thereAreNoItemsAvailableFilter: "there are no items available with the chosen filter combination. Please change it to find more items.",
  thereAreNoCharactersAvailableFilter:
    "there are no characters available with the chosen filter combination. Please change it to find more characters.",
  clearFilters: "clear filters",
  thereAreNoItemsInTheShop: "there are no items in the shop",
  thereAreNoCharactersInTheShop: "there are no characters in the shop",
  thereAreNoItemsAvailable: "there are no items available in the shop. Wait for items to be placed in the shop",
  thereAreNoCharactersAvailable: "there are no characters available. Wait for characters to be placed in the shop",
  sellDescription: "you're listing your item for sale on the shop. The marketplace will add a 10% royalty fee and 3% platform fee on-top.",
  marketplaceFees: "the purchase price consists of the list price, a 10% royalty fee and a 3% platform fee",
};
