apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    spec:
      containers:
        - name: ui
          image: "eu.gcr.io/web3-335312/kread/frontend-staging/frontend:latest"