SDK_PATH = /Users/WietzeS/Kryha/agoric/agoric-sdk
KREAD_REPO = /Users/carlostrigo/kryha/agoric/code/Agoric/agoric/contract/src/index.js

# changes by making scenario2
KEPLR_ADDRESS = agoric10s7qs6cznnmswahwzh9lak6pac6we5k86qvnt8
