SDK_PATH = /Users/carlostrigo/kryha/agoric/agoric-sdk
KREAD_REPO = /Users/carlostrigo/kryha/agoric/code/Agoric/agoric/contract/src/index.js

# changes by making scenario2
KEPLR_ADDRESS = agoric1tq3v943uaycqp90qvuyaqzwdc3eh52xzrcl4p6
