import { CharacterItems, Item } from "../interfaces";
import {
  AirResevoir1,
  Background1,
  Clothing1,
  FrontMask1,
  Hair7,
  HeadPiece1,
  Liquid1,
  Mask1,
  MidBackground1,
  Noseline1,
} from "../assets/icons";

export const FakeCharacterItems: CharacterItems = {
  noseline: {
    name: "AirTox: Fairy Dust Elite",
    category: "noseline",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Noseline1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  midBackground: {
    name: "AirTox: Fairy Dust Elite",
    category: "mid background",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: MidBackground1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  mask: {
    name: "AirTox: Fairy Dust Elite",
    category: "mask",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Mask1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  headPiece: {
    name: "AirTox: Fairy Dust Elite",
    category: "head piece",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: HeadPiece1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  hair: {
    name: "AirTox: Fairy Dust Elite",
    category: "hair",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Hair7,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  frontMask: {
    name: "AirTox: Fairy Dust Elite",
    category: "front mask",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: FrontMask1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  liquid: {
    name: "AirTox: Fairy Dust Elite",
    category: "liquid",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Liquid1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  background: {
    name: "AirTox: Fairy Dust Elite",
    category: "background",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Background1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  airResevoir: {
    name: "AirTox: Fairy Dust Elite",
    category: "air resevoir",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: AirResevoir1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  clothing: {
    name: "AirTox: Fairy Dust Elite",
    category: "clothing",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Clothing1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
};

export const Items: Item[] = [
  {
    name: "AirTox: Fairy Dust Elite",
    category: "noseline",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Noseline1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "mid background",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: MidBackground1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "mask",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Mask1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "head piece",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: HeadPiece1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "hair",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Hair7,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "front mask",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: FrontMask1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "liquid",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Liquid1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "background",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Background1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "air resevoir",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: AirResevoir1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
  {
    name: "AirTox: Fairy Dust Elite",
    category: "clothing",
    id: "12333",
    description: "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: Clothing1,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#968996", "#FFFFFF"],
    projectDescription: "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    price: 1234,
    details: {
      boardAddress: "0x0177812bsjs7998",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: [],
    },
    date: "23213123",
    slots: [],
  },
];
