import { Character } from "../interfaces";
import { FakeCharacterItems } from "./fake-item-data";

export const FakeCharcters: Character[] = [
  {
    title: "character 1",
    image: "",
    keyId: 1,
    // date: 1657803039,
    name: "character 1",
    type: "Tempet Scavenger",
    id: "7999",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 1,
    items: FakeCharacterItems,
    detail: {
      boardId: "06553",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: [
      {
        name: "transfer",
        price: 1234,
        to: "0x0177812bsjs7998",
        from: "0x0177812bsjs7998",
        date: 1235667272,
      },
    ],
    // price: 123123,
  },
  {
    title: "character 2",
    image: "",
    keyId: 1,
    // date: 1657803039,
    name: "character 2",
    type: "Tempet Scavenger",
    id: "78991",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 2,
    items: FakeCharacterItems,
    detail: {
      boardId: "06553",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: [
      {
        name: "transfer",
        price: 1234,
        to: "0x0177812bsjs7998",
        from: "0x0177812bsjs7998",
        date: 1235667272,
      },
    ],
    // price: 123123,
  },
  {
    title: "character 3",
    image: "",
    keyId: 1,
    // date: 1657803039,
    name: "character 3",
    type: "Tempet Scavenger",
    id: "78993",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 3,
    items: FakeCharacterItems,
    detail: {
      boardId: "06553",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: [
      {
        name: "transfer",
        price: 1234,
        to: "0x0177812bsjs7998",
        from: "0x0177812bsjs7998",
        date: 1235667272,
      },
    ],
    // price: 123123,
  },
  {
    title: "character 4",
    image: "",
    keyId: 1,
    // date: 1657803039,
    name: "character 4",
    type: "Tempet Scavenger",
    id: "78991",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 4,
    items: {},
    detail: {
      boardId: "06553",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: [
      {
        name: "transfer",
        price: 1234,
        to: "0x0177812bsjs7998",
        from: "0x0177812bsjs7998",
        date: 1235667272,
      },
    ],
    // price: 123123,
  },
];

export const FakeCharctersNoItems: any[] = [
  {
    title: "character 1",
    image: "",
    name: "character 1",
    type: "Tempet Scavenger",
    id: "7899",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 1,
    items: [], //FakeCharacterItems,
    detail: {
      boardId: "06553",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: {
      event: "0x0177812bsjs7998",
      price: 1234,
      to: "0x0177812bsjs7998",
      from: "0x0177812bsjs7998",
      date: "1235667272",
    },
    price: 123123,
  },
  {
    title: "RAMIRO",
    image: "",
    name: "RAMIRO",
    type: "Tempet Scavenger",
    id: "7899",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 1,
    items: [],
    detail: {
      boardId: "06553",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: {
      event: "0x0177812bsjs7998",
      price: 1234,
      to: "0x0177812bsjs7998",
      from: "0x0177812bsjs7998",
      date: "1235667272",
    },
    price: 123123,
  },
  {
    title: "character 2",
    image: "",
    name: "character 2",
    type: "Tempet Scavenger",
    id: "78992",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 1,
    items: [], //FakeCharacterItems,
    detail: {
      boardId: "06553",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: {
      event: "0x0177812bsjs7998",
      price: 1234,
      to: "0x0177812bsjs7998",
      from: "0x0177812bsjs7998",
      date: "1235667272",
    },
    price: 123123,
  },
  {
    title: "character 3",
    image: "",
    url: "https://builder.agoric.kryha.dev/static/media/default-character.216ad02c.png",
    name: "character 3",
    type: "Tempet Scavenger",
    id: "78991",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 1,
    items: [],
    detail: {
      boardId: "06553",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: {
      event: "0x0177812bsjs7998",
      price: 1234,
      to: "0x0177812bsjs7998",
      from: "0x0177812bsjs7998",
      date: "1235667272",
    },
    price: 123123,
  },
  {
    title: "character 4",
    image: "",
    url: "https://builder.agoric.kryha.dev/static/media/default-character.216ad02c.png",
    name: "character 4",
    type: "Tempet Scavenger",
    id: "78991",
    description:
      "A Tempet Scavenger has Tempet technology, which is, own modification on the standard requirements and regulations on tech that is allowed. Agreed among the cities. Minimal and elegant, showcasing their water technology filtration system that is known throughout that land as having the best mask when it comes to scent tracking technology.",
    level: 1,
    items: {},
    detail: {
      boardId: "06553",
      contractAddresss: "0x0177812bsjs7998",
      standard: "standard",
      artist: "emily",
      metadata: "https://yourmetadata.info",
    },
    projectDescription: "this is a project",
    itemActivity: {
      event: "0x0177812bsjs7998",
      price: 1234,
      to: "0x0177812bsjs7998",
      from: "0x0177812bsjs7998",
      date: "1235667272",
    },
    price: 123123,
  },
];
