import { CharacterItems } from "../interfaces";
import {
  AirResevoir1,
  Background1,
  Clothing1,
  FrontMask1,
  Hair7,
  HeadPiece1,
  Liquid1,
  Mask1,
  MidBackground1,
  Noseline1,
} from "../assets/icons";

export const Items: CharacterItems = {
  noseline: [
    {
      name: "noseline",
      id: "12332",
      code: "nl",
      image: Noseline1,
      equipped: false,
      category: "noseline",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "noseline",
      id: "12332",
      code: "nl",
      image: Noseline1,
      equipped: false,
      category: "noseline",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "noseline",
      id: "12332",
      code: "nl",
      image: Noseline1,
      equipped: true,
      category: "noseline",
      price: 12.0943,
      amount: 13,
    },
  ],
  midBackground: [
    {
      name: "mid background",
      id: "12332",
      code: "bg I",
      image: MidBackground1,
      equipped: true,
      category: "mid background",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mid background",
      id: "12332",
      code: "bg I",
      image: MidBackground1,
      equipped: false,
      category: "mid background",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mid background",
      id: "12332",
      code: "bg I",
      image: MidBackground1,
      equipped: false,
      category: "mid background",
      price: 12.0943,
      amount: 13,
    },
  ],
  mask: [
    {
      name: "mask",
      id: "12332",
      code: "M",
      image: Mask1,
      equipped: true,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "M",
      image: Mask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
  ],
  headPiece: [
    {
      name: "head piece",
      id: "12332",
      code: "HP",
      image: HeadPiece1,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece1,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece1,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece1,
      equipped: true,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece1,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
  ],
  hair: [
    {
      name: "hair",
      id: "12332",
      code: "h",
      image: Hair7,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "hair",
      id: "12332",
      code: "h",
      image: Hair7,
      equipped: true,
      category: "hair",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "hair",
      id: "12332",
      code: "h",
      image: Hair7,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
  ],
  frontMask: [
    {
      name: "Front mask",
      id: "12332",
      code: "f",
      image: FrontMask1,
      equipped: true,
      category: "front mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "Front mask",
      id: "12332",
      code: "f",
      image: FrontMask1,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "Front mask",
      id: "12332",
      code: "f",
      image: FrontMask1,
      equipped: false,
      category: "front mask",
      price: 12.0943,
      amount: 13,
    },
  ],
  liquid: [
    {
      name: "liquid",
      id: "12332",
      code: "L",
      image: Liquid1,
      equipped: true,
      category: "liquid",
      price: 12.0943,
      amount: 13,
    },
  ],
  background: [
    {
      name: "background",
      id: "12332",
      code: "bg II",
      image: Background1,
      equipped: true,
      category: "background",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "background",
      id: "12332",
      code: "bg II",
      image: Background1,
      equipped: false,
      category: "background",
      price: 12.0943,
      amount: 13,
    },
  ],
  airResevoir: [
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir1,
      equipped: true,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir1,
      equipped: false,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir1,
      equipped: false,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir1,
      equipped: false,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
  ],
  clothing: [
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing1,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing1,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing1,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing1,
      equipped: true,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing1,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing1,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
  ],
};
