import { CharacterItems } from "@agoric/types";
import {
  AirResevoir1,
  AirResevoir2,
  AirResevoir3,
  AirResevoir4,
  Background1,
  Background2,
  Clothing1,
  Clothing2,
  Clothing3,
  Clothing4,
  Clothing5,
  Clothing6,
  FrontMask1,
  FrontMask2,
  FrontMask3,
  Hair10,
  Hair7,
  Hair8,
  HeadPiece1,
  HeadPiece2,
  HeadPiece3,
  HeadPiece4,
  HeadPiece5,
  Mask1,
  Mask2,
  Mask3,
  Mask4,
  Mask5,
  Mask6,
  Mask7,
  Mask8,
  MidBackground1,
  MidBackground2,
  MidBackground3,
  Noseline1,
  NoseLine2,
  Noseline3
} from "../../assets/icons";

export const Items: CharacterItems = {
  noseline: [
    {
      name: "noseline",
      id: "12332",
      code: "nl",
      image: Noseline1,
      equipped: false,
      category: "noseline",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "noseline",
      id: "12332",
      code: "nl",
      image: NoseLine2,
      equipped: false,
      category: "noseline",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "noseline",
      id: "12332",
      code: "nl",
      image: Noseline3,
      equipped: true,
      category: "noseline",
      price: 12.0943,
      amount: 13,
    },
  ],
  midBackground: [
    {
      name: "mid background",
      id: "12332",
      code: "bg I",
      image: MidBackground1,
      equipped: true,
      category: "mid background",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mid background",
      id: "12332",
      code: "bg I",
      image: MidBackground2,
      equipped: false,
      category: "mid background",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mid background",
      id: "12332",
      code: "bg I",
      image: MidBackground3,
      equipped: false,
      category: "mid background",
      price: 12.0943,
      amount: 13,
    },
  ],
  mask: [
    {
      name: "mask",
      id: "12332",
      code: "M",
      image: Mask1,
      equipped: true,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "M",
      image: Mask2,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask3,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask4,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask5,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask6,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask7,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "mask",
      id: "12332",
      code: "m",
      image: Mask8,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
  ],
  headPiece: [
    {
      name: "head piece",
      id: "12332",
      code: "HP",
      image: HeadPiece1,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece2,
      equipped: true,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece3,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece4,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "head piece",
      id: "12332",
      code: "hp",
      image: HeadPiece5,
      equipped: false,
      category: "head piece",
      price: 12.0943,
      amount: 13,
    },
  ],
  hair: [
    {
      name: "hair",
      id: "12332",
      code: "h",
      image: Hair7,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "hair",
      id: "12332",
      code: "h",
      image: Hair8,
      equipped: true,
      category: "hair",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "hair",
      id: "12332",
      code: "h",
      image: Hair10,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
  ],
  frontMask: [
    {
      name: "Front mask",
      id: "12332",
      code: "f",
      image: FrontMask1,
      equipped: true,
      category: "front mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "Front mask",
      id: "12332",
      code: "f",
      image: FrontMask2,
      equipped: false,
      category: "mask",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "Front mask",
      id: "12332",
      code: "f",
      image: FrontMask3,
      equipped: false,
      category: "front mask",
      price: 12.0943,
      amount: 13,
    },
  ],
  liquid: [],
  background: [
    {
      name: "background",
      id: "12332",
      code: "bg II",
      image: Background1,
      equipped: true,
      category: "background",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "background",
      id: "12332",
      code: "bg II",
      image: Background2,
      equipped: false,
      category: "background",
      price: 12.0943,
      amount: 13,
    },
  ],
  airResevoir: [
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir1,
      equipped: true,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir2,
      equipped: false,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir3,
      equipped: false,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "air resevoir",
      id: "12332",
      code: "ar",
      image: AirResevoir4,
      equipped: false,
      category: "air resevoir",
      price: 12.0943,
      amount: 13,
    },
  ],
  clothing: [
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing1,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing2,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing3,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing4,
      equipped: true,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing5,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
    {
      name: "clothing",
      id: "12332",
      code: "c",
      image: Clothing6,
      equipped: false,
      category: "clothing",
      price: 12.0943,
      amount: 13,
    },
  ],
};
