import { Item, ItemEquip } from "../../interfaces";
import {
  TempetAddons,
  TempetAddonsThumbnail,
  TempetBackground1,
  TempetBackground1Thumbnail,
  TempetBackground2,
  TempetBackground2Thumbnail,
  TempetClothing,
  TempetClothingThumbnail,
  TempetFilter1,
  TempetFilter1Thumbnail,
  TempetFilter2,
  TempetFilter2Thumbnail,
  TempetHair,
  TempetHairThumbnail,
  TempetHeadpiece,
  TempetHeapieceThumbnail,
  TempetMask,
  TempetMaskThumbnail,
  TempetStyleline,
  TempetStylelineThumbnail
} from "../../assets";


export const mockItems: Item[] = [
  {
    name: "NoseLine: Fairy Dust Elite",
    category: "noseline",
    id: "1",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetStyleline,
    thumbnail: TempetStylelineThumbnail,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#000006", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06111",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16534919770812,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16534919770811,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770811,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770812,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Mid Background: Fairy Dust Elite",
    category: "background",
    id: "2",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetBackground1,
    thumbnail: TempetBackground1Thumbnail,
    level: 64,
    rarity: 200,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06110",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770813,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16524919770814,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770815,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770816,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Mask: Fairy Dust Elite",
    category: "mask",
    id: "3",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetMask,
    thumbnail: TempetMaskThumbnail,
    level: 64,
    rarity: 200,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06129",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770817,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16523919770817,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770818,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770819,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Head Piece: Fairy Dust Elite",
    category: "headPiece",
    id: "4",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetHeadpiece,
    thumbnail: TempetHeapieceThumbnail,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#7B5B7B", "#0000006"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 1653491997000,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 1653491937000,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770819,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 1653471987000,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Hair: Fairy Dust Elite",
    category: "hair",
    id: "5",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetHair,
    thumbnail: TempetHairThumbnail,
    level: 64,
    rarity: 10,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06128",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770819,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16524919770818,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16522919770817,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770815,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Front Mask: Fairy Dust Elite",
    category: "frontMask",
    id: "6",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetAddons,
    thumbnail: TempetAddonsThumbnail,
    level: 64,
    rarity: 1,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#3063A5"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770816,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16524919770814,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770813,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770812,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Liquid: Fairy Dust Elite",
    category: "airReservoir",
    id: "7",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetFilter1,
    thumbnail: TempetFilter1Thumbnail,
    level: 64,
    rarity: 30,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#7B5B7B", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770811,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770811,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770812,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770813,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Background: Fairy Dust Elite",
    category: "midBackground",
    id: "8",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetBackground2,
    thumbnail: TempetBackground2Thumbnail,
    level: 64,
    rarity: 1,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#3063A5"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770814,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770815,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770816,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770817,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Air Reservoir: Fairy Dust Elite",
    category: "airReservoir",
    id: "9",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetFilter1,
    thumbnail: TempetFilter1Thumbnail,
    level: 64,
    rarity: 30,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#3063A5", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770818,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770819,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770829,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770828,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Clothing: Fairy Dust Elite",
    category: "clothing",
    id: "10",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetClothing,
    thumbnail: TempetClothingThumbnail,
    level: 64,
    rarity: 100,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#7B5B7B", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770827,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770826,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770825,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770824,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    name: "Air reservoir 2: Fairy Dust Elite",
    category: "liquid",
    id: "12339",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetFilter2,
    thumbnail: TempetFilter2Thumbnail,
    level: 64,
    rarity: 30,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#3063A5", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770823,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770822,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770821,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 1653491987000,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
];

export const mockItemsEquipped: ItemEquip[] = [
  {
    isEquipped: false,
    isForSale: false,
    name: "NoseLine: Fairy Dust Elite",
    category: "noseline",
    id: "1",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetStyleline,
    thumbnail: TempetStylelineThumbnail,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#000006", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06111",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16534919770812,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16534919770811,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770811,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770812,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Mid Background: Fairy Dust Elite you know whgat it is",
    category: "midBackground",
    id: "2",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetBackground1,
    thumbnail: TempetBackground1Thumbnail,
    level: 64,
    rarity: 200,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06110",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770813,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16524919770814,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770815,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770816,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Mask: Fairy Dust Elite",
    category: "mask",
    id: "3",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetMask,
    thumbnail: TempetMaskThumbnail,
    level: 64,
    rarity: 200,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#B1A2A2", "#7B5B7B", "#968996", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06129",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770817,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16523919770817,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770818,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770819,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Head Piece: Fairy Dust Elite",
    category: "headPiece",
    id: "4",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetHeadpiece,
    thumbnail: TempetHeapieceThumbnail,
    level: 64,
    rarity: 300,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#7B5B7B", "#0000006"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 1653491997000,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 1653491937000,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770819,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 1653471987000,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Hair: Fairy Dust Elite",
    category: "hair",
    id: "5",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetHair,
    thumbnail: TempetHairThumbnail,
    level: 64,
    rarity: 10,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "06128",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770819,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16524919770818,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16522919770817,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770815,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Front Mask: Fairy Dust Elite",
    category: "frontMask",
    id: "6",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetAddons,
    thumbnail: TempetAddonsThumbnail,
    level: 64,
    rarity: 1,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#3063A5"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770816,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16524919770814,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16524919770813,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16524919770812,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Liquid: Fairy Dust Elite",
    category: "airReservoir",
    id: "7",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetFilter1,
    thumbnail: TempetFilter1Thumbnail,
    level: 64,
    rarity: 30,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#7B5B7B", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16524919770811,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770811,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770812,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770813,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Background: Fairy Dust Elite",
    category: "background",
    id: "8",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetBackground2,
    thumbnail: TempetBackground2Thumbnail,
    level: 64,
    rarity: 1,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#3063A5"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770814,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770815,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770816,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770817,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Air Reservoir: Fairy Dust Elite",
    category: "airReservoir",
    id: "9",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetFilter1,
    thumbnail: TempetFilter1Thumbnail,
    level: 64,
    rarity: 30,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#3063A5", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770818,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770819,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770829,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770828,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Clothing: Fairy Dust Elite",
    category: "clothing",
    id: "10",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetClothing,
    thumbnail: TempetClothingThumbnail,
    level: 64,
    rarity: 100,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#7B5B7B", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770827,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770826,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770825,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 16525919770824,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
  {
    isEquipped: false,
    isForSale: false,
    name: "Air reservoir 2: Fairy Dust Elite",
    category: "liquid",
    id: "12339",
    description:
      "This is an all-purpose air filter and air temperature regulator with minimal water analyzing technology. Suitable for warm hostile places, weather, and contaminated areas. Not so good for the dead zone.",
    image: TempetFilter2,
    thumbnail: TempetFilter2Thumbnail,
    level: 64,
    rarity: 30,
    effectiveness: 12,
    layerComplexity: 78,
    forged: "Tempet Section 1",
    baseMaterial: "Mars & Earth",
    colors: ["#0000006", "#3063A5", "#FFFFFF"],
    projectDescription:
      "In a far-future post-apocalyptic world, after multiple generations of war, we ended up with limited set of land, resources, water, and food. By leveraging decentralized technology humanity has found equilibrium in the management of global resources by decentrally managing the supply and demand based on everyone's contribution to the global ecosystem. The scavengers are the eyes and ears outside the city walls called the wildland.Carrying the most advanced technology allowed by the city counsels.Modified For: survival, traceability, stealth, and attack. Scavengers are usually promoted to bounty hunters of the state.Carrying out justice on their behalf in the wildlands.",
    details: {
      boardId: "0x0177812bsjs7998",
      brand: "0x0177812bsjs7998",
      artist: "emily",
      metadata: "",
    },
    date: "23213123",
    activity: [
      {
        name: "transfer",
        from: "totoro",
        to: "hayao",
        date: 16525919770823,
      },
      {
        name: "sale",
        from: "totoro",
        to: "hayao",
        date: 16525919770822,
      },
      {
        name: "transfer",
        from: "goku",
        to: "shinji",
        date: 16525919770821,
      },
      {
        name: "sale",
        from: "batman",
        to: "hayao",
        date: 1653491987000,
      },
      {
        name: "mint",
        from: undefined,
        to: "nakamoto",
        date: 1652168177,
      },
    ],
  },
];
