name: Skaffold Build PR Check

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Skaffold 
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin/
      shell: bash

    - name: Skaffold build precheck
      run: |
        cd frontend
        export $(grep -v '^#' .env.emerynet | xargs)
        envsubst < skaffold.emerynet.template.yaml > skaffold.emerynet.yaml
        skaffold build --filename skaffold.emerynet.yaml
      shell: bash
 

