name: Yarn Build PR Check

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install project dependencies
      run: yarn install

    - name: Yarn Build
      run: cd frontend && yarn build
